export const ActionTypes = {
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
    SET_TREES: "SET_TREES",
    SELECTED_TREE: "SELECTED_TREE",
    REMOVE_SELECTED_TREE: "REMOVE_SELECTED_TREE",
  };